version: '3'

services:
  client:
    build: .
    ports:
      - "3000:3000"
    container_name: chat-client
  server:
    build: ../BE
    ports:
      - "8080:8080"
    container_name: chat-server
